server:
  host: "localhost"
  port: 8080

databases:
  users:
    host: "localhost"
    port: 5432
    user: "******"
    password: "******"
    database: "user_details"

redis:
  host: "localhost"
  port: 6379
  password: "redis_password"
