server:
  host: "localhost"
  port: 8080

databases:
  user_detail:
    host: "localhost"
    port: 5432
    user: "******"
    password: "******"

redis:
  host: "localhost"
  port: 6379
  password: "redis_password"
