openapi: 3.0.0
info:
  title: User API
  version: v1
  description: API for managing users
servers:
  - url: http://localhost:8080/template-service/api/v1
    description: Development server
paths:
  /users:
    post:
      summary: Create a new user
      description: Creates a new user with the provided details.
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserRequest'
      responses:
        200:
          description: User created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        400:
          description: Invalid request body
        500:
          description: Internal server error
    get:
      summary: Get user by email
      description: Retrieves a user by their email address.
      parameters:
        - in: query
          name: email
          schema:
            type: string
          required: true
          description: Email address of the user
        - in: query
          name: password
          schema:
            type: string
          required: true
          description: password to authenticate the data
      responses:
        200:
          description: User found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        404:
          description: User not found
        500:
          description: Internal server error
components:
  schemas:
    User:
      type: object
      properties:
        id:
          type: string
          format: uuid
          description: Unique identifier of the user
        name:
          type: string
          description: Name of the user
        email:
          type: string
          format: email
          description: Email address of the user
        metadata:
          type: string
          description: Additional metadata about the user
        created_at:
          type: string
          format: date-time
          description: Timestamp when the user was created
        updated_at:
          type: string
          format: date-time
          description: Timestamp when the user was last updated
        deleted_at:
          type: string
          format: date-time
          description: Timestamp when the user was deleted (if applicable)
    UserRequest:
      type: object
      properties:
        name:
          type: string
          description: Name of the user
          required: true
        email:
          type: string
          format: email
          description: Email address of the user
          required: true
        password:
          type: string
          description: Password of the user
          required: true
        metadata:
          type: string
          description: Additional metadata about the user
